---
- name: Ensure portainer directories exist
  become: true
  file:
    group: "{{ portainer__deploy_group }}"
    owner: "{{ portainer__deploy_user }}"
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ portainer__deploy_dir }}"
    - "{{ portainer__data_dir }}"
  when: not portainer__use_nfs

- name: Ensure portainer directories exist
  become: true
  file:
    group: "{{ portainer__deploy_group }}"
    owner: "{{ portainer__deploy_user }}"
    path: "{{ item }}"
    state: directory
    recurse: yes
  with_items:
    - "{{ portainer__deploy_dir }}"
    - "{{ portainer__volume_dir }}"
  when: portainer__use_nfs

- name: Copy files
  become: true
  template:
    dest: "{{ portainer__deploy_dir }}/portainer.yml"
    group: "{{ portainer__deploy_group }}"
    owner: "{{ portainer__deploy_user }}"
    src: "templates/portainer.yml.j2"
  when: 
    - portainer__state == "started"
    - not portainer__use_nfs

- name: Copy files
  become: true
  template:
    dest: "{{ portainer__deploy_dir }}/portainer.yml"
    group: "{{ portainer__deploy_group }}"
    owner: "{{ portainer__deploy_user }}"
    src: "templates/portainer-nfs.yml.j2"
  when: 
    - portainer__state == "started"
    - portainer__use_nfs

- name: Debug portainer variables
  debug:
    msg:
      - "portainer__deploy_dir: {{ portainer__deploy_dir }}"
      - "portainer__volume_dir: {{ portainer__volume_dir }}"
      - "portainer__state: {{ portainer__state }}"
      - "nfs__ip: {{ nfs__ip }}"

- name: Start portainer
  command: docker stack deploy -c portainer.yml portainer
  args:
    chdir: "{{ portainer__deploy_dir }}"
  when: portainer__state == "started"

- name: Stop portainer
  command: docker stack rm portainer
  args:
    chdir: "{{ portainer__deploy_dir }}"
  when: portainer__state == "stopped"