portainer__volume_dir: "{{ portainer__deploy_dir }}"  # Defaults to deploy_dir
portainer__data_dir: "{{ portainer__volume_dir }}/data"
portainer__deploy_dir: /mnt/data/portainer
portainer__deploy_group: root
portainer__deploy_user: root

portainer__network: public

portainer__state: started

portainer__version: 2.21.5

traefik: true
use_nfs_server: false
nfs__ip: 0.0.0.0
portainer__nfs_volume_dir: "/mnt/nfs/portainer"